services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: GET-Food-Server
    restart: always
    ports:
      - 172.18.0.3:5000:5000
    expose:
      - 5000

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: GET-Food-Client
    restart: always
    ports:
      - 192.168.1.239:80:80
    expose:
      - 80