services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: GET-Food-Server
    restart: always
    ports:
      - 127.0.0.1:5000:5000
    expose:
      - 5000

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: GET-Food-Client
    restart: always
    ports:
      - 127.0.0.1:80:80
    expose:
      - 80