services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: GET-Food-Client
    restart: always
    ports:
      - 192.168.1.239:80:80 # Change the IP here to your internal production IP
    expose:
      - 80