services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
     - ./:/var/www
     - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - api-network
    depends_on:
      - api-server
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GET-Food-API
    #command: gunicorn --bind 0.0.0.0:8000 --chdir server --workers 4 "app:app"
    volumes:
      - ./:/var/www
    networks:
      - api-network
        #aliases:
        #  - api-network

networks:
  api-network: